### ISSUE TITLE
Can't push to repo!

### ISSUE THREAD

**Issue by capn-freako** [conal/linalg#16]
In trying to push to a newly created development branch, I'm getting:

```
$ git push --set-upstream origin infra-clean
ERROR: Permission to conal/linalg.git denied to capn-freako.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by bolt12** [comment]
Yes, you need permissions. Another way to do it is to fork this repo, and push the changes to that repo and then open a PR in this repo and wait for it to be merged!

**Comment by conal** [comment]
I’ve not made you (or anyone else) a collaborator.

Any suggestions or insights about a safe & convenient workflow? I want to broadly encourage people to offer contributions without necessary giving access to push to or merge into master.

**Comment by bolt12** [comment]
The safe & convenient workflow I'm used to is the one I described above!

You can look at the following resources for more details: 

- https://github.com/firstcontributions/first-contributions
- https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by conal** [comment]
Thanks for the suggestion and references\! Are there downsides to forking the repo rather than having collaborator permissions (or similar)?

**Comment by bolt12** [comment]
Well, having collaborators makes sense just from an administrative
standpoint. Even if everyone had permissions to push to the master branch
it is considered a good practice to still follow the workflow I mentioned.

**Comment by conal** [comment]
Thanks for these suggestions. So, instead of each of us making dev branches (as I’ve done) in a shared repo, we each clone the repo and issue PRs? Should I transfer the project to a new organization, and then make my own personal clone, too?

**Comment by bolt12** [comment]
Yes, each branch should tackle a specific issue, just to keep PR somewhat
atomic and the workflow consistent and easy to track.

It's up to you if you want to do that. I know people who did that, I know
people who didn't, I guess it's just a preference ( I might be wrong). But
I think that for now it's best if we keep things simple, so probably keep
the repo as it is and as it grows will see what happens! :)

**Comment by dwincort** [comment]
@conal I think you giving up ownership and making your own fork is a little overkill -- who would have the authority to actually approve merges?

The only downside to forking that I know of is that it can get a little confusing for people with forked repos when there are a lot of changes -- you need to keep track of _your_ version of master vs the _upstream_ version.

For the record, you can also configure special branches (like master) that require PR approval before merges are allowed.  You can also set code owners for specific directories or files that determine who needs to provide approval.  This is my personal preferred method for ongoing collaboration.  I find it a little easier to manage than managing pulls, merges, and fetches across forks.  The method @bolt12 suggests is, of course, exactly what is required when you have outside contributors.

Even in my own personal code repos, I set up master so no one (including myself) can merge to it directly.  Every change to master goes through a PR (although, if I'm the only one working on the repo, I can obviously approve my own PRs).

**Comment by bolt12** [comment]
Yes, I agree!

**Comment by conal** [comment]
Thanks for all the input\! I have a lot to learn about collaboration, and I hope you will all nudge me with suggestions for making things smoother and more fun for all of us.

**Comment by capn-freako** [comment]
I like Daniel's proposal, that is, allow the 4 of us to work in this repo
as collaborators, but protecting the *master* branch (i.e. - only Conal can
allow merges into it). And, cooperatively, agreeing to do all work on
"atomic" development branches, using pull requests as our medium of
discussion for such new code development. This approach has the advantage
that it's easier for two or more of us to collaborate easily on some
development branch. (Might be harder, if we were each confined to only our
own fork of this repo.)

Daniel, did I paraphrase your suggestion correctly?

-db

**Comment by conal** [comment]
I'm happy with forking or with collaborators. I like Dan's suggestion of disabling direct pushes to master for everyone.

**Comment by dwincort** [comment]
@conal Since it's your repo, it's up to you to make the decision.  Once you do, please state it here and close this issue.

**Comment by conal** [comment]
Okay. I'll leave it as is for now. If the current arrangement chafes for anyone, please say so.
