### ISSUE TITLE
What about products in L?

### ISSUE THREAD

**Issue by dwincort** [conal/linalg#2]
The current definition of `L` is:
```haskell
data L :: (* -> *) -> (* -> *) -> (* -> *) where
  Zero :: L f g s
  Scale :: s -> L Par1 Par1 s
  JoinL :: V h => h (L f g s) -> L (h :.: f) g s
  ForkL :: V h => h (L f g s) -> L f (h :.: g) s
```
This n-ary representation of join and fork feels nice, but it's also limiting.  For instance, how do you represent a matrix with 7 rows?  You'll need a representable functor `h` that has cardinality 7.  There's no way to build it up from smaller components using the machinery here.  In other words, there's no way to join a 5x2 matrix with a 2x2 matrix to get a 7x2 matrix.

The obvious way to fix this is to support constructors like
```haskell
  JoinL' :: V h => h (L f g s) -> h' (L f g s) -> L (h :*: h') g s
  ForkL' :: V h => h (L f g s) -> h' (L f g s) -> L f (h :*: h') s
```
but I'm not sure what the repercussions are.  At the very least, operations become much more cumbersome because there are so many constructors.

**Comment by conal** [comment]
Thanks. I agree and have been adding binary nonuniform join & fork, essentially as you’ve suggested. Working out very nicely. Almost ready to commit.

**Comment by bolt12** [comment]
Since this might be develop into more structured discussions as we go on on the design space I suggest every commit to be a separate Pull Request so people can better keep track and discuss things before merge.

**Comment by conal** [comment]
Thanks for the suggestion. I just made pull request \#9. I wasn’t sure whether to merge before or after discussion. I chose the former, because I want to fix issue \#4 as well as a separate pull request. Can you still discuss after I merge?

I don’t have much experience with collaborative GitHub work, and I appreciate feedback & advice.

**Comment by bolt12** [comment]
Yes you can still discuss after merge! It was a good idea to create a new "experimental" branch.

**Comment by conal** [comment]
> But I don’t see any need for `ins` and `exs`. They do not make sense to me. Maybe I’m wrong here but `inl`/`inr` and `exl` and `exr` suffice.

@bolt12: Given my previous comment in this thread, do you now see the sense/meaning and purpose/value of `ins` and `exs` and the insufficiency of `(inl,inr)` and `(exl,exr)` in the presence of n-ary coproducts?

IIRC, you had inquired more generally a few days ago about n-ary {,co,bi}products vs binary and about functor composition vs product. If you think more clarification could help on these fundamental questions—including the relationship of trie functors and their corresponding index types (“logarithms”)—would you please add issue?

**Comment by bolt12** [comment]
I do see now the need for those and am clarified! Thanks for taking the time to explain! I can safely close this issue now :smile:

**Comment by conal** [comment]
Oops! I meant to post my reply at PR #18. I'm going to delete my comment and move @bolt12's there.
