### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by conal** [conal/linalg#29]
Would be nice to have it.

I've seen projects using [haskell-ci](https://github.com/haskell-CI/haskell-ci).

**Comment by bolt12** [comment]
I can add CI with GitHub Actions and support a couple of GHC versions. I'm currently also into Nix and can try and set up a build environment or add Nix to CI, but I think that can wait for now

**Comment by bolt12** [comment]
Maybe it makes more sense to add CI when the project is more stable, what do you think?

**Comment by dwincort** [comment]
I guess the question is what are we checking?  There's no test suite or anything -- would this just be a check to make sure the code compiles?  I guess that could be nice, but this project is small and simple enough (and lacks a test suite) right now that I don't think we're in danger of someone merging a PR that has broken code in it.  Also, no one is currently depending on it, so it's not like we're in danger of breaking something for users.

Or, are you proposing we write a test suite?

**Comment by conal** [comment]
I was just thinking of a Travis setup that compiles our source on a few versions of GHC. I always compile on one before pushing, and I’m guessing you all do as well, so let’s wait until something pinches or we have a test suite. As for testing, I’d wait until we have a precise and runnable denotational model (linear functions), which will then induce a bunch of homomorphism properties. In addition to letting us prove and calculate code, most of these homomorphisms will be testable.

I’m closing this issue for now.
