### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by bolt12** [conal/linalg#3]
Very impressive! I have a lot of questions:

> `JoinL :: V h => h (L f g s) -> L (h :.: f) g s`

Why `h :.: f`? Shouldn't it be `:*:` instead of `:.:`?

If I understand correctly, here it seems that we can only Join/Fork "n-ary" matrices of the same shape. I do not know if that is too restrictive since Join, for example, should be able to join matrices with the same number of rows but different number of columns. Maybe I'm not understanding correctly how to construct a matrix out of this inductive type. I tried doing:

```haskell
:t Join (Par1 (Scale 3))
Join (Par1 (Scale 3)) :: Num s => L (Par1 :.: Par1) Par1 s
```

Which makes sense because 1 x 1 = 1, but how would I join more matrices? I tried `Join ((Scale 3) :*: (Scale 3))` intuitively but didn't work. Oh I see, I tried:

```haskell
:t Join (Par1 (Scale 3) :*: Par1 (Scale 3))
Join ((Par1 (Scale 3) :*: Par1 (Scale 3))) :: Num s => L ((Par1 :*: Par1) :.: Par1) Par1 s
```

And it worked! Awesome! What's going on behind this that makes it work?

But as I said, I think it should be possible to do something like:

`a = Join (Par1 (Scale 3) :*: Par1 (Scale 3))`

and then

`:t Join (Par1 a :*: Par1 (Scale 3))`

But it doesn't work because it expects 'a' to be a 1x1 matrix.

Maybe we should give it some Show instance to help seeing what's going on.

Overall it seems to have a lot of potential! I'm curious to see if the Khatri Rao product can be easily typeable. I think it should be something like this:

`khatri :: V h => h (L f j s) :.: g (L f j s) -> L f (h :.: g) s`

Because the khatri-rao of two matrices A = 3x4 and B = 3x5, should yield a matrix C = 3x(4x5) = 3x20, so the Khatri-Rao product can be seen like matrix pairing.

But looking at it, I think this type signature can also be employed by ForkL since it is more general (might be wrong here, once again I'm still trying to figure out how this works). If this is the case I'm not sure if we should allow "n-ary" Joins and Forks.

**Comment by conal** [comment]
Thanks for these questions and comments\! I guess there are at least two different issues here. If you break this feedback into separate issues with suitable names, we’ll be able to address and resolve them separately, and others who have related questions can find the answers as well.

**Comment by bolt12** [comment]
Sure thing! So one for the "n-ary" restriction and other for the "khatri rao product"

**Comment by conal** [comment]
Thank you! Please close issue when the more specific ones are in place.

**Comment by bolt12** [comment]
See #10. Regarding the other issue it has already been asked, we can carry the discussion about that in #9 I think

**Comment by conal** [comment]
Thanks!
