### ISSUE TITLE
Type (category) names for linear maps and their representations

### ISSUE THREAD

**Issue by conal** [conal/linalg#37]
I want to have three representations of the linear maps, each defined in its own module, each supporting exactly the same vocabulary, with each pair related by simple, well-defined isomorphisms over that vocabulary. The three representations:

  - The semantics: linear maps/*functions*.
  - Conventional matrices but generalized from numerically indexed vectors to arbitrary representable functors.
  - The compositional scale/join/fork variant of matrices we’ve been focusing on.

I’d appreciate name suggestions. The vocabulary on linear maps will be the central specification, with the same vocabulary on matrices and the compositional variant being defined via their required isomorphism properties.

**Comment by bolt12** [comment]
The semantics representation is the `F (f s -> g s)`, right? this can be called `LinearMapS s f g` (Linear Map Semantic)

The conventional matrices generalized to representable functors are what type? something like `V g (V f s) s` ? Then this can be called `LinearMapMV` (Linear Map Matrix Vector)

The inductive matrix definition can be called `LinearMapMC` or `LinearMapMI` (Linear Map Matrix Compositional/Inductive)

I'm not very good with names :stuck_out_tongue:

**Comment by snowleopard** [comment]
I like to think about the three representations of linear maps as "functions", "matrices" and "terms", where the latter refers to the little language defined by the scale/fork/join primitives.

**Comment by dwincort** [comment]
I tend to be pretty uncreative with names, but here are my thoughts.

I agree that the semantic representation should look something like:
```haskell
newtype F s f g = F (f s -> g s)
```
The choice of `F` for "function" makes sense if we want single character names, but it is perhaps too terse.

I think the "conventional" form should probably have the type:
```haskell
newtype M s f g = M (g (f s))
```
Obviously, `M` is for "matrix".  Another concise option could be `RM` for "representable matrix", especially if we think we may have other matrix-like representations in the future.

The type for the compositional form is already given (what we've been calling `L`), but I think it needs a new name.  I like @bolt12's suggestions of both `I` and `C` for inductive and compositional.

If we want names than are longer than one character, then we could prefix them all with `LinearMap` as @bolt12 suggests, or perhaps just `LMap`.  That would give us `LMapF`, `LMapM`, and `LMapC`.

**Comment by snowleopard** [comment]
The newtypes `F` and `M` seem fine to me. 

One possible interpretation for `L` could be "language". In the same spirit, one could use `T` or `E` for "term(s)" or "expression(s)".

The term/suffix "compositional" seems potentially confusing because both functions and matrices are pretty compositional too, each in a different sense.

The term/suffix "inductive" seems less confusing in this respect, but it's an adjective whereas `F` and `M` stand for nouns. That's why I prefer nouns like "term", "expression" or "language".

**Comment by conal** [comment]
Thanks for the discussion!

**Comment by conal** [comment]
> I like to think about the three representations of linear maps as “functions”, “matrices” and “terms”, where the latter refers to the little language defined by the scale/fork/join primitives.

I guess the (representable, non-inductive) matrix type forms a language as well, though with a much less interesting grammar, since it’s not inductive. `L` more so since it is inductive, but still there are non-trivial/non-semantic equalities like the join/fork exchange laws that I wouldn’t expect to hold in a language. I suppose we could consider a more literal form of equality to distinguish from denotational equality for both the non-inductive and inductive “matrices”, though we couldn’t expose such an operation without creating an abstraction leak.

**Comment by conal** [comment]
> The term/suffix “inductive” seems less confusing in this respect, but it’s an adjective whereas F and M stand for nouns.

I agree that inductive is more specifically descriptive. Nice point about noun vs adjective.

**Comment by conal** [comment]
Come to think of it, there are two non-inductive matrix types: row-major and column-major. My personal habit is to use row-major, but I don’t think that choice is any more natural than column-major.

**Comment by conal** [comment]
Another idea is to use the same name for all three, say “`LinearMap`”, “`Linear`” or “`L`”, and distinguish by module name. We can use descriptive module names like “`LinearFunction`”, say “`import LinearFunction qualified as F`” and still have terse uses. Most client code would probably choose a single representation and import unqualified. Changing representations then requires editing a single `import`. As long as all exported functionality shares a common vocabulary and is specified via denotational homomorphisms and implemented correctly (thus no abstraction leak), the visible results will be identical.

I’m now leaning strongly in this direction.

**Comment by conal** [comment]
Another internal representation (with the same denotation and vocabulary) I think we’ll want is numerically indexed arrays, with all numeric indexing generated safely and automatically via isomorphisms as in [*Data-Parallel Programming without Arrays*](http://conal.net/papers/data-parallel-programming-without-arrays).

**Comment by dwincort** [comment]
I second the idea of naming through modules.  It also allows us to use longer, more descriptive names (as you say, like `LinearFunction`) and let the importer decide how terse they want to be.

I've written down some simple transformations between these different types, although I haven't done any work to prove that they're the correct components of isomorphisms:
```haskell
newtype F s f g = F { unF :: f s -> g s }

newtype M s f g = M { unM :: g (f s) }

lToM :: (V f, ToRowMajor g) => L f g s -> M s f g
lToM = M . lToRowMaj

mToL :: (V f, ToRowMajor g) => M s f g -> L f g s
mToL = rowMajToL . unM

lToF :: Semiring s => L f g s -> F s f g
lToF = F . (@@)

mToF :: (V2 f g, Semiring s) => M s f g -> F s f g
mToF (M gfs) = F $ \fs -> dot fs <$> gfs
  where dot x y = sum $ liftR2 (*) x y
```
You'll notice that I don't have transformations from a function (`F`) to one of the other representations — I haven't figured that one out.  I'm sure I must need to use representability somehow, but I can't quite get it to work.  Maybe there are other necessary constraints?

**Comment by conal** [comment]
> You’ll notice that I don’t have transformations from a function (`F`) to one of the other representations — I haven’t figured that one out.

This one’s a nice puzzle. It’s a delightful property of linear maps that an entire function between infinite types can be captured losslessly into a few numbers. A testament to the severity of linearity. (The elegant proof that it is so gives a conversion algorithm.) And wonderful that such a restricted notion can be so very useful.

**Comment by bolt12** [comment]
I think it needs to use the same idea that I used in #34 and use the basis somehow

**Comment by conal** [comment]
> I think it needs to use the same idea that I used in \#34 and use the basis somehow

A linear map is determined by its behavior on a basis, a fact I used in the compiling-to-categories work to extract a matrix from a linear function. Thinking about linear maps compositionally, however, yields a more elegant solution, which is really already implicit in our current code.

**Comment by bolt12** [comment]
Are you saying that it's straightforward to implement the conversions than?
I'm curious to know how to do it elegantly! Do you have any pointers?

**Comment by dwincort** [comment]
Ahh, I think I see.  We can define:
```haskell
fToM :: (V2 f g, Semiring s) => F s f g -> M s f g
fToM (F f) = M $ distribute $ f <$> unM idM
```
where `idM` is the identity in `M` (i.e., `idM = diagRep zero (pureRep one)`).  Doing it compositionally for `L` is the same idea but a little bit more work because you need to handle the different cases you might come across.  (Of course, you could always define `fToL = mToL . fToM`.)

**Comment by conal** [comment]
> Are you saying that it’s straightforward to implement the conversions than? I’m curious to know how to do it elegantly\! Do you have any pointers?

Yes. Consider that for any pair-consuming linear map `h :: a :* b :-* c`, `h = f ||| g` (binary join). Similarly for pair-producing linear maps, and for “n-tuple”-consuming and -producing linear maps (where `n` needn’t be a number). Finally, every linear map from scalars to scalars has the form `(s *)` for some scalar valued s. Each of these claims can be proved from linearity. Moreover, scaling (curried multiplication), join, and fork (n-ary and uncurried binary) are all *isomorphisms*, so we can invert them. In other words, one can always recursively decompose linear functions (over a fairly broad range of trie/representable functors) into non-inductive or into inductive “matrices”.

These isomorphisms are embodied in the pattern synonyms in `LinAlg`. In that context, we sometimes have an `L` structure from which to determine functor structure, e.g., addition and composition. When we don’t have that structure, we instead use type classes, as in `rowToL`. Come to think of it, we probably don’t need `lToRow` to be a method, since it takes an `L` as argument.

For linear functions and for non-inductive matrices, we need to lean more heavily on type classes.

Come to think of it, we can probably replace all of our type classes with one.

``` haskell
-- | Known shapes
data VShape :: (* -> *) -> * where
  Par1S :: VShape Par1
  (:*:#) :: VShape a -> VShape b -> VShape (a :*: b)
  (:.:#) :: VShape b -> VShape a -> VShape (b :.: a)
  GenericS :: Generic1 a => VShape (Rep1 a) -> VShape a
```

**Comment by dwincort** [comment]
This `VShape` data type looks a lot like the `Shape` data type that I defined in https://github.com/conal/linalg/pull/32:
```haskell
data Shape a where
  IsPar :: Shape Par1
  IsProd :: (V a, V b) => Shape (a :*: b)
  IsComp :: (V' h, V a) => Shape (h :.: a)

class HasShape a where
  shape :: Shape a

instance                HasShape Par1      where shape = IsPar
instance (V a, V  b) => HasShape (a :*: b) where shape = IsProd
instance (V a, V' h) => HasShape (h :.: a) where shape = IsComp
```
I didn't include the `GenericS` shape (which I guess is for an arbitrary `Representable` functor?), but otherwise they're very close.  Note that in my implementation the `V` constraint includes `HasShape` (and `V'` is `V` without `HasShape`) — I think in practice this means my version requires more calls to `shape` with type applications.  I'm not sure which one I like better.

**Comment by conal** [comment]
Hah\! Terrific. I’m afraid I fell behind in last week’s exchanges while preparing for my Haskell Love talk. Sorry about that\!

**Comment by capn-freako** [comment]
> In other words, one can always recursively decompose linear functions (over a fairly broad range of trie/representable functors) into non-inductive or into inductive “matrices”.

@conal , what is the difference here between _inductive_ and _non-inductive_ matrices?

**Comment by conal** [comment]
@capn-freako The “inductive matrix” representation is defined recursively/“inductively”. Correspondingly, basic operations on that representation will be implemented recursively as well (even if derived automatically by GHC). In contrast, the non-inductive matrix representation is a nested pair of (representable) functors, and operations won’t be defined recursively. (Each functor may or may not be defined inductively.)
