### ISSUE TITLE
David's Questions on LinAlg.hs

### ISSUE THREAD

**Issue by capn-freako** [conal/linalg#5]
1. What is the fundamental difference between `sequenceA` (a.k.a. - `transpose`) and `distribute`?
They both swap the outer-most two functors, but are clearly not the same.

1. What is the purpose of your two `pattern` definitions (`Fork` and `Join`)?
Are they just conveniences, or do they get you around some Haskell syntax blockage?

1. You haven’t mentioned/defined any category-like things, and yet your machinery looks complete; how did that work out?

1. Why doesn’t `(L (f :.: Par1) (f :.: Par1) s)` need an `Additive` instance?
And would it have, had you decided to introduce _Abelian_ categories?

**Comment by conal** [comment]
Thanks for these questions and comments\! If you break this feedback into separate issues with suitable names (at least for questions that still interest you), we’ll be able to address and resolve them separately, and others who have related questions can find the answers as well.

**Comment by conal** [comment]
And then please close this issue when the others are in place.

**Comment by capn-freako** [comment]
First 3 questions given their own issues, as per our agreement.
Question 4 was unnecessary. I just missed it in the code. (Thanks, Daniel!)

**Comment by conal** [comment]
Thanks!
