### ISSUE TITLE
Pattern purpose

### ISSUE THREAD

**Issue by bolt12** [conal/linalg#8]
What's the purpose of the following patterns:

```haskell
pattern Fork :: V h => h (L f g s) -> L f (h :.: g) s
pattern Fork ms <- (unforkL -> ms) where Fork = ForkL
{-# complete Fork #-}

pattern Join :: V h => h (L f g s) -> L (h :.: f) g s
pattern Join ms <- (unjoinL -> ms) where Join = JoinL
{-# complete Join #-}
```

?

I'm not very familiar with the concept and never have used it in Haskell.

**Comment by conal** [comment]
I wanted to capture the fact that fork and join are both *isomorphisms* and make it convenient to view linear maps as forks or joins whenever the types allow them to be.

This way, individual operations such as composition don’t need to explicitly reshape representations. For instance, note the following clauses for linear map addition:

``` haskell
  (f :|# g) + (h :| k) = (f + h) :| (g + k)
  (f :&# g) + (h :& k) = (f + h) :& (g + k)
  ForkL ms  + Fork ms' = Fork (liftR2 (+) ms ms')
  JoinL ms  + Join ms' = Join (liftR2 (+) ms ms')
```

The type synonyms cause the second argument in each clause to get reshaped as needed to match the shape of the corresponding first argument, resulting in code that closely resembles basic properties of abelian categories, including linear algebra.

**Comment by conal** [comment]
An explanation I wrote in my notes and then forgot:

The fork and join operations (whether binary nonuniform or n-ary uniform) are *isomorphisms*. For instance, not only can we fork two linear maps with common domain to get a linear map to pairs, but *every* linear map to pairs is a fork. Similarly for join, and similarly for n-ary uniform fork and join. Pattern matching is about invertibility/injectivity, allowing one to write in terms of forward operations, implying the inverse computation without having to say it explicitly. Pattern synonyms give us the notational convenience of pattern matching without the rigidity of directly mirroring the representation. For instance, the `Fork` pattern matches a literal `ForkL`, but also sometimes a `JoinL`.
